// Shared by deploy.js and package.js: (re)generate source/Config.brs from the
// deploy-time environment so the channel zip carries its API URL, Plex user
// id, and (optionally) a device auth key. Always regenerated so a stale
// value from a previous run can't linger in the build.
//
//   ROKU_API_URL        e.g. http://192.168.1.181:3001
//   ROKU_PLEX_USER_ID   e.g. 1001793 (sent as X-Plex-User)
//   ROKU_AUTH_KEY       per-device auth key — normally leave UNSET and let the
//                       channel pair on first run; the backend rejects a stale
//                       key outright, while keyless LAN reads are allowed.

const fs = require('fs');
const path = require('path');

const escape = (s) => String(s || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');

function writeConfigBrs(rootDir) {
  const apiUrl = (process.env.ROKU_API_URL || '').trim();
  const plexUserId = (process.env.ROKU_PLEX_USER_ID || '').trim();
  const authKey = (process.env.ROKU_AUTH_KEY || '').trim();
  const configBrs = `' GENERATED by scripts/config.js — do not commit.
' Embeds deploy-time configuration into the channel so values like the
' API URL persist across reinstalls and reboots without depending on
' the device registry. Re-run \`npm run deploy\` / \`npm run package\` to regenerate.

function configApiUrl() as string
    return "${escape(apiUrl)}"
end function

function configPlexUserId() as string
    return "${escape(plexUserId)}"
end function

function configAuthKey() as string
    return "${escape(authKey)}"
end function
`;
  fs.writeFileSync(path.join(rootDir, 'source', 'Config.brs'), configBrs, 'utf-8');
  console.log(apiUrl ? `Baked ROKU_API_URL → ${apiUrl}` : 'ROKU_API_URL not set — channel will fall back to registry value.');
  console.log(plexUserId ? `Baked ROKU_PLEX_USER_ID → ${plexUserId}` : 'ROKU_PLEX_USER_ID not set — backend will see anonymous requests.');
  console.log(authKey ? `Baked ROKU_AUTH_KEY (length=${authKey.length})` : 'ROKU_AUTH_KEY not set — channel will pair on first run (recommended).');
}

// The channel's file set — the single source of truth for what ships in
// the zip. fonts/ was missing from package.js for a long time (KNOWN-ISSUES
// #1), which would have shipped a store package without the Settings gear
// glyph font.
const CHANNEL_FILES = [
  'manifest',
  'source/**/*',
  'components/**/*',
  'images/**/*',
  'fonts/**/*',
];

module.exports = { writeConfigBrs, CHANNEL_FILES };
